# Generated by Django 3.2.4 on 2021-06-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='Uploads/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
